language: rust

rust:
    - nightly

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

script:
    cargo build -v;
    cargo test -v;

after_success: |
    [ $TRAVIS_RUST_VERSION = nightly ] &&
    wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=KDi7Rnv9IHVos7gsifOYFAURwDoGaM0vQ --exclude-pattern=/.cargo target/kcov $(ls target/debug/hpc_allocator_rust-* | grep -v '.d$')

